Repository entando-k8s/entando-quarkus-parent, pull requests merged in 2021-11, with the labels that each got.

#5 ENG-2678 - Vulnerabilities suppression
  owasp-dependency-check-suppression.xml
Labels: size/S

#6 ENG-2968 Fixing vulnerabilities
  .snyk
  pom.xml
Labels: size/L, approved

#7 ENG-2968 Rolling back keycloak version update
  pom.xml
Labels: size/XS, approved

#8 ENG-2968 Updating snyk suppression file
  .snyk
  owasp-dependency-check-suppression.xml
Labels: size/S, approved
